// @ts-check
/**
 * @fileoverview GET /api/exit-plan/latest — Retrieve the most recently generated exit plan.
 *
 * The ExitPlanCard component polls this endpoint every 3 seconds (via React Query)
 * to check whether a new exit plan has been generated by the voice concierge.
 *
 * State is held in-memory per serverless instance. In production this should be
 * replaced with a persistent store (Vercel KV, Redis, or a database) to survive
 * cold starts and share state across instances.
 *
 * @module api/exit-plan/latest
 */

import { setCors } from '../_lib/helpers.js';

/**
 * In-memory exit plan store.
 * Resets on serverless cold start — acceptable for a demo environment.
 *
 * @type {import('./generate.js').ExitPlan | null}
 */
let lastExitPlan = null;

/**
 * Updates the in-memory exit plan.
 * Called by the voice concierge pipeline after generating a new plan.
 *
 * @param {import('./generate.js').ExitPlan} plan - The newly generated exit plan.
 * @returns {void}
 */
export function setLastExitPlan(plan) {
  lastExitPlan = plan;
}

/**
 * Latest exit plan handler.
 * Returns the current in-memory exit plan, or null if none has been generated yet.
 *
 * @param {import('@vercel/node').VercelRequest}  req - Incoming request (no params needed).
 * @param {import('@vercel/node').VercelResponse} res - Response: { success: true, data: ExitPlan | null }
 * @returns {void}
 *
 * @example
 * // GET /api/exit-plan/latest
 * // → { success: true, data: null }  (before any plan is generated)
 * // → { success: true, data: { title: "...", steps: [...], ... } }
 */
export default function handler(req, res) {
  setCors(res);
  if (req.method === 'OPTIONS') return res.status(200).end();
  res.json({ success: true, data: lastExitPlan });
}
